repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      files: \.py$
    # Run the formatter.
    - id: ruff-format
      files: \.py$
      args: [--config, format.quote-style = 'single']
